[package]
name = "netmate-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
redis = "0.25.4"
scylla = "0.13.1"
thiserror = "1.0.61"
tokio = "1.38.0"
uuid = "1.10.0"