[package]
name = "netmate-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
redis = { version = "0.25.4", features = ["tokio-comp"]}
scylla = "0.13.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.1"
thiserror = "1.0.61"
tokio = "1.38.0"
uuid = { version = "1.10.0", features = ["serde"] }